name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: phiph-s/metermonitor-managementserver

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_PAT }}
  
        - name: Extract Info
          id: extract_info
          shell: bash
          run: |
            VERSION=$(jq -r '.version' config.json)
            echo "version=${VERSION}" >> $GITHUB_OUTPUT

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
             
        - name: Build and push container image
          uses: docker/build-push-action@v6.13.0
          id: docker_build
          with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: |
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_info.outputs.version }} 
            labels: |
              org.opencontainers.image.title="Meter Monitor"
              org.opencontainers.image.description="Integrate ESP32 based meter monitor cams with Home Assistant using AI"
              org.opencontainers.image.vendor=HSRM
              org.opencontainers.image.authors="Philipp Seelos"
              org.opencontainers.image.url=https://github.com/phiph-s/metermonitor-managementserver
              org.opencontainers.image.source=https://github.com/phiph-s/metermonitor-managementserver
              org.opencontainers.image.version=${{ steps.extract_info.outputs.version }}
              io.hass.name="Meter Monitor"
              io.hass.url=https://github.com/phiph-s/metermonitor-managementserver
              io.hass.version=${{ steps.extract_info.outputs.version }}
              io.hass.type=addon
              io.hass.arch=armv7|aarch64|amd64
            annotations: |
              org.opencontainers.image.title="Meter Monitor"
              org.opencontainers.image.description="Integrate ESP32 based meter monitor cams with Home Assistant using AI"
              org.opencontainers.image.vendor=HSRM
              org.opencontainers.image.authors="Philipp Seelos"
              org.opencontainers.image.version=${{ steps.extract_info.outputs.version }}
              org.opencontainers.image.url=https://github.com/phiph-s/metermonitor-managementserver             
           
  
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}      
